package org.jboss.soa.esb.listeners.lifecycle;

import java.util.EventListener;

/**
 * This interface represents the lifecycle events generated by a managed instance.
 */
public interface ManagedLifecycleEventListener extends EventListener {
 
    public void stateChanged(final ManagedLifecycleStateEvent event) ;
}
